services:  
  postgres:
    container_name: pf.database
    image: postgres
    restart: always
    environment:
        POSTGRES_DB: "petfoster"
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "postgres"
    ports:
        - 5433:5432
    volumes:
        - postgres-data:/var/lib/postgresql/data
    
volumes:
    postgres-data:
